# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 07332c395707e19e560f4ebd15764cb1141a628f1bedac16ed954ebe876b409cf4351d442b826efeffa0cef02434efca2dde2106124ba43f4899adf422d6b043

test:
  secret_key_base: af3f5ff4d20a991ee9e41c061e39d188938025c623791017ac14ed2b5156364eab8f576a91e57e6f0c331c6dcba95e17920adc7581126b36a694841abb09030a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
